export const getInvestments       = ()        => window.electronAPI.getInvestments()
export const updateInvestments    = (data)    => window.electronAPI.updateInvestments(data)
export const getInvestmentHistory = ()        => window.electronAPI.getInvestmentHistory()
export const fetchStockPrices     = (tickers) => window.electronAPI.fetchStockPrices(tickers)
export const upsertStock          = (t, s)    => window.electronAPI.upsertStock(t, s)
export const removeStock          = (ticker)  => window.electronAPI.removeStock(ticker)
export const updateStockValue     = (value)   => window.electronAPI.updateStockValue(value)
export const addStockSale         = (t, p)    => window.electronAPI.addStockSale(t, p)
export const getHysaTransactions     = ()       => window.electronAPI.getHysaTransactions()
export const addHysaTransaction      = (data)   => window.electronAPI.addHysaTransaction(data)
export const deleteHysaTransaction   = (id)     => window.electronAPI.deleteHysaTransaction(id)
export const getHysaSource           = ()       => window.electronAPI.getHysaSource()
export const syncHysaBalance         = ()       => window.electronAPI.syncHysaBalance()
export const exportBackup            = ()       => window.electronAPI.exportBackup()
export const inspectBackup           = ()       => window.electronAPI.inspectBackup()
export const restoreBackup           = (opts)   => window.electronAPI.restoreBackup(opts)
export const linkBrokerageHosted     = ()       => window.electronAPI.linkBrokerageHosted()
export const getBrokerageAccounts    = ()       => window.electronAPI.getBrokerageAccounts()
export const syncHoldings            = ()       => window.electronAPI.syncHoldings()
export const removeBrokerage         = (id)     => window.electronAPI.removeBrokerage(id)
export const getHoldings             = ()       => window.electronAPI.getHoldings()
export const linkCardHosted          = ()       => window.electronAPI.linkCardHosted()
export const relinkCardHosted        = (id)     => window.electronAPI.relinkCardHosted(id)
export const cancelHostedLink        = ()       => window.electronAPI.cancelHostedLink()
export const getSpendingAccounts     = ()       => window.electronAPI.getSpendingAccounts()
export const removeSpendingAccount   = (id)     => window.electronAPI.removeSpendingAccount(id)
export const syncTransactions        = ()       => window.electronAPI.syncTransactions()
export const getSpendingTransactions = ()       => window.electronAPI.getSpendingTransactions()
export const getSpendingCategories   = ()       => window.electronAPI.getSpendingCategories()
export const setTransactionCategory  = (id, c, r) => window.electronAPI.setTransactionCategory(id, c, r)
export const setTransactionSplit     = (id, w) => window.electronAPI.setTransactionSplit(id, w)
