const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('electronAPI', {
  getInvestments:       ()           => ipcRenderer.invoke('get-investments'),
  updateInvestments:    (data)       => ipcRenderer.invoke('update-investments', data),
  upsertEtf:            (t, v)       => ipcRenderer.invoke('upsert-etf', t, v),
  removeEtf:            (ticker)     => ipcRenderer.invoke('remove-etf', ticker),
  getInvestmentHistory: ()           => ipcRenderer.invoke('get-investment-history'),
  fetchStockPrices:     (tickers)    => ipcRenderer.invoke('fetch-stock-prices', tickers),
  upsertStock:          (t, s)       => ipcRenderer.invoke('upsert-stock', t, s),
  removeStock:          (ticker)     => ipcRenderer.invoke('remove-stock', ticker),
  updateStockValue:        (value)   => ipcRenderer.invoke('update-stock-value', value),
  addStockSale:            (t, p)    => ipcRenderer.invoke('add-stock-sale', t, p),
  getHysaTransactions:     ()        => ipcRenderer.invoke('get-hysa-transactions'),
  addHysaTransaction:      (data)    => ipcRenderer.invoke('add-hysa-transaction', data),
  deleteHysaTransaction:   (id)      => ipcRenderer.invoke('delete-hysa-transaction', id),
  updateHysaBalance:       (value)   => ipcRenderer.invoke('update-hysa-balance', value),
  linkCardHosted:          ()        => ipcRenderer.invoke('link-card-hosted'),
  cancelHostedLink:        ()        => ipcRenderer.invoke('cancel-hosted-link'),
  getSpendingAccounts:     ()        => ipcRenderer.invoke('get-spending-accounts'),
  removeSpendingAccount:   (itemId)  => ipcRenderer.invoke('remove-spending-account', itemId),
  syncTransactions:        ()        => ipcRenderer.invoke('sync-transactions'),
  getSpendingTransactions: ()        => ipcRenderer.invoke('get-spending-transactions'),
  getSpendingCategories:   ()        => ipcRenderer.invoke('get-spending-categories'),
  setTransactionCategory:  (id, c, r) => ipcRenderer.invoke('set-transaction-category', id, c, r),
})
